services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - vendor:/var/www/vendor  # Vendor'u ayrı volume yap
            - node_modules:/var/www/node_modules  # Node modules da ayrı
        networks:
            - laravel
    webserver:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - vendor:/var/www/vendor  # Nginx için de aynı vendor volume
            - ./docker/nginx:/etc/nginx/conf.d
        networks:
            - laravel
    db:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel
networks:
    laravel:
        driver: bridge
volumes:
    dbdata:
        driver: local
    vendor:  # Vendor volume'u ekle
        driver: local
    node_modules:  # Node modules volume'u ekle
        driver: local
